name: Simple proxy - workflow test
env:
  SHARED_CACHE: /mnt/shared

on:
  push:
    branches:
      - dev

jobs:
  build-and-push-docker:
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push dev image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kaiv-dev/simple-proxy:dev
          cache-from: type=local,src=${{env.SHARED_CACHE}}
          cache-to: type=local,dest=${{env.SHARED_CACHE}},mode=max

