name: Build and push docker image


on:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string
      shared_cache:
        required: false
        type: string
        default: /mnt/shared

env:
  SHARED_CACHE: /mnt/shared
  CARGO_TERM_COLOR: always


jobs:
  build-and-push-docker:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kaiv-dev/simple_proxy:${{ inputs.channel }}
          cache-from: type=local,src=${{ inputs.shared_cache }}/${{ inputs.channel }}
          cache-to: type=local,dest=${{ inputs.shared_cache }}/${{ inputs.channel }},mode=max