name: Simple proxy build and push docker image
env:
  SHARED_CACHE: /mnt/shared

on:
  push:
    branches:
      - nightly
      - master

jobs:
  build-and-push-docker:
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/kaiv-dev/simple_proxy:${{ github.event.inputs.channel || github.ref_name }}
          cache-from: type=local,src=${{ env.SHARED_CACHE }}/${{ github.event.inputs.channel || github.ref_name }}
          cache-to: type=local,dest=${{ env.SHARED_CACHE }}/${{ github.event.inputs.channel || github.ref_name }},mode=max